apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: simplevat
  name: simplevat-dev-rep-{RELEASE-TAG}
  namespace: simplevat-dev
spec:
  replicas: 3
  selector:
    app: simplevat
    deployment: v-{RELEASE-TAG}
  template:
    metadata:
      labels:
        app: simplevat
        deployment: v-{RELEASE-TAG}
    spec:
      containers:
        - name: simplevat
          image: gcr.io/simplevat-dev/simplevat:{RELEASE-TAG}
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
          env:
            - name: SIMPLEVAT_SMTP_USER
              value: support@simplevat.com
            - name: SIMPLEVAT_SMTP_PASS
              value: $impleVat@123
            - name: SIMPLEVAT_SMTP_HOST
              value: smtp.gmail.com
            - name: SIMPLEVAT_SMTP_PORT
              value: "587"
            - name: SIMPLEVAT_SMTP_AUTH
              value: "true"
            - name: SIMPLEVAT_SMTP_STARTTLS_ENABLE
              value: "true"
            - name: SIMPLEVAT_ENVIRONMENT
              value: dev
            - name: SIMPLEVAT_SUBDOMAIN
              value: dev
            - name: SIMPLEVAT_TOKEN
              value: XXXX
            - name: SIMPLEVAT_RELEASE
              value: {RELEASE-TAG}
            - name: SIMPLEVAT_DB_HOST
              value: 34.68.185.169
            - name: SIMPLEVAT_DB
              value: simplevat_db
            - name: SIMPLEVAT_DB_USER
              value: proxyuser
            - name: SIMPLEVAT_DB_PASSWORD
              value: SimpleVat123$
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
#            - name: SIMPLEVAT_DB_USER
#              valueFrom:
#                secretKeyRef:
#                  name: cloudsql-db-credentials
#                  key: username
#            - name: SIMPLEVAT_DB_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: cloudsql-db-credentials
#                  key: password
            # [END cloudsql_secrets]
        # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # [START proxy_container]
#        - name: cloudsql-proxy
#          image: gcr.io/cloudsql-docker/gce-proxy:1.11
#          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
#                    "-instances=simplevat-dev:us-central1:simplevat-dev-db-new=tcp:3306",
#                    "-credential_file=/secrets/cloudsql/credentials.json"]
#          securityContext:
#            runAsUser: 2  # non-root user
#            allowPrivilegeEscalation: false
#          volumeMounts:
#            - name: cloudsql-instance-credentials
#              mountPath: /secrets/cloudsql
#              readOnly: true
#            - name: ssl-certs
#              mountPath: /etc/ssl/certs
#            - name: cloudsql
#              mountPath: /cloudsql
#        # [END proxy_container]
#      # [START volumes]
#      volumes:
#        - name: cloudsql-instance-credentials
#          secret:
#            secretName: cloudsql-instance-credentials
#        - name: cloudsql
#          emptyDir:
#        - name: ssl-certs
#          hostPath:
#            path: /etc/ssl/certs
#      # [END volumes]
